### ISSUE TITLE
SETranslateNMD creates empty results zip file (user interface)

### ISSUE THREAD

**Issue by robertfisher002** [flemingtonlab/SpliceTools#1]
Hi,

I tried 2 of my rMATs SE output files and the example SE files but all three return empty zip files when I click on results. Other than that, this is a nice splicing analysis tool!

Robert

**Comment by nungerleider** [comment]
Thanks Robert. Let me look into this and get back to you in a couple of hours.

**Comment by nungerleider** [comment]
You were right - I think it should be fixed now.
