### ISSUE TITLE
mm10 bed12 file to share?

### ISSUE THREAD

**Issue by NayeliGutierrez** [flemingtonlab/SpliceTools#10]
Hello,

Thank you for this helpful tool! I was wondering if anyone has a mm10 BED12 file they’d be willing to share?

Thanks in advance!
Nayeli

**Comment by mbaddoo** [comment]
Hello, Nayeli-

Glad you find SpliceTools helpful.  Attached is mm10 BED12.  It has '.txt' extension for the purpose of attaching it so feel free to remove this extension after downloading.  Please give it a try and let me know if you have any trouble with it.  
Best-
Melody
[mm10.bed.txt](https://github.com/user-attachments/files/17756899/mm10.bed.txt)

**Comment by NayeliGutierrez** [comment]
Hi Melody, thank you so much for your quick response and for sharing the file!

Best,
Nayeli
