### ISSUE TITLE
While function loses last record

### ISSUE THREAD

**Issue by kk988** [flemingtonlab/SpliceTools#2]
https://github.com/flemingtonlab/SpliceTools/blob/644a3c266f5135afc37063c57e6a24adea2feadc/bin/SENumberSkipped.pl#LL142-L165

The last record is added to `@previous_amplitude_array` - but it is never printed to deduplicated.tsv file.

You need to basically do https://github.com/flemingtonlab/SpliceTools/blob/644a3c266f5135afc37063c57e6a24adea2feadc/bin/SENumberSkipped.pl#LL157-L159  one more time after the while loop.

**Comment by mbaddoo** [comment]
kk988-

Thank you for bringing this to our attention.  We will resolve this issue soon. 

mbaddoo

**Comment by erikflemington** [comment]
Thanks again for finding these issues, kk998. This one has also been corrected.
