### ISSUE TITLE
SENumberSkipped - printing line to wrong IncDiff file

### ISSUE THREAD

**Issue by kk988** [flemingtonlab/SpliceTools#3]
Hi,

I also noticed another bug. In this section of code: https://github.com/flemingtonlab/SpliceTools/blob/main/bin/SENumberSkipped.pl#L313-L326.  
You are processing a new gene, so you want to print out the highest exons skipped transcript of the previous gene, however you are printing it to the neg_incDiff file or pos_incDiff file based on the *new* transcript's IncDiff, rather than the max_count_line's IncDiff. 

This results in some transcripts being printed to the wrong folder (transcripts with positive incdiff are being printed to negative incdiff files/folders). 

To clearly see the error happening, add a print statement above where the lines are printed (L315 and L320) like so: `print "PRINTING $max_counts_line to NEGATIVE ($IncDiff) - SEID $SE_ID\n\n";` The line being printed will have a different IncDiff than `$IncDiff`. 

Bug doesn't provide incorrect results (to my knowledge) but the results are mixed up in neg incdiff and pos incdiff files. 

Thanks!

**Comment by erikflemington** [comment]
Thank you for finding this issue and even providing the fix. Problem has been corrected.
