### ISSUE TITLE
How to generate BED12 annotation?

### ISSUE THREAD

**Issue by leli-li** [flemingtonlab/SpliceTools#5]
Hi,

Can you tell me how to generate BED12 annotation from a gtf format? Thank you!

**Comment by mbaddoo** [comment]
Hello @leli-li -

There are a number of ways you can convert gtf to BED12.  One of the easier ways to achieve is to use the attached python script (remove .txt extension after downloading) for the conversion.  

Usage:  python gtf2bed.py input.gtf > output.bed


[gtf2bed.py.txt](https://github.com/flemingtonlab/SpliceTools/files/12739982/gtf2bed.py.txt)

Best-
:)
